# Generated by Django 6.0.4 on 2026-07-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zuck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=50)),
                ('avatar', models.CharField(verbose_name=50)),
                ('description', models.CharField(verbose_name=50)),
                ('author', models.CharField(verbose_name=50)),
                ('elements', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
