# Generated by Django 6.0.4 on 2026-07-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuck',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zuck',
            name='avatar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zuck',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='zuck',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
