# Generated by Django 6.0.4 on 2026-07-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zucks', '0002_alter_zuck_author_alter_zuck_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuck',
            name='name',
            field=models.CharField(default='undefined', max_length=100),
            preserve_default=False,
        ),
    ]
